export default {
  nav: { home: 'होम', search: 'खोजीं', dashboard: 'डैशबोर्ड', profile: 'प्रोफ़ाइल', login: 'लॉगिन', register: 'रजिस्टर', logout: 'लॉगआउट', about: 'हमरे बारे में', contact: 'संपर्क', language: 'भाषा', pharmacyMap: 'दवाई दुकान मैप', interactions: 'दवाई इंटरैक्शन', healthProfile: 'सेहत प्रोफ़ाइल', expiryTracker: 'एक्सपायरी ट्रैकर', prescriptionScan: 'पर्ची स्कैन', verifyMedicine: 'दवाई जाँच', trending: 'ट्रेंडिंग', priceCompare: 'दाम तुलना', orders: 'हमार ऑर्डर' },
  home: { title: 'रउआ के स्मार्ट दवाई साथी', subtitle: 'दवाई खोजीं, दाम तुलना करीं, आ सेहत जानकारी पाईं — सब एक जगह।', searchPlaceholder: 'दवाई, लक्षण, या सेहत सवाल खोजीं...', features: 'विशेषता', cta: 'शुरू करीं' },
  search: { title: 'दवाई खोजीं', placeholder: 'नाम, ब्रांड, या संरचना से खोजीं...', results: 'परिणाम', noResults: 'कवनो परिणाम ना मिलल', tryAgain: 'दोसर शब्द आज़माईं' },
  medicine: { name: 'दवाई के नाम', brand: 'ब्रांड', composition: 'संरचना', price: 'दाम', stock: 'स्टॉक', available: 'उपलब्ध', limited: 'सीमित', outOfStock: 'स्टॉक में नइखे', prescription: 'पर्ची चाहीं', precautions: 'सावधानी', sideEffects: 'दुष्प्रभाव', uses: 'उपयोग', alternatives: 'विकल्प', dosage: 'खुराक', manufacturer: 'निर्माता' },
  pharmacy: { name: 'दवाई दुकान', distance: 'दूरी', rating: 'रेटिंग', open: 'अभी खुलल बा', closed: 'बंद बा', directions: 'रास्ता', timings: 'समय', verified: 'सत्यापित', call: 'फोन करीं' },
  interactions: { title: 'दवाई इंटरैक्शन चेकर', subtitle: 'जाँचीं कि रउआ के दवाई साथे सुरक्षित बा', addMedicine: 'दवाई जोड़ीं', checkInteractions: 'जाँच करीं', safe: 'सुरक्षित', caution: 'सावधानी से', risky: 'जोखिम भरा', dangerous: 'खतरनाक', noInteractions: 'कवनो इंटरैक्शन ना मिलल', severity: 'गंभीरता', recommendation: 'सिफारिश' },
  healthProfile: { title: 'सेहत प्रोफ़ाइल', subtitle: 'व्यक्तिगत सलाह खातिर सेहत जानकारी', allergies: 'एलर्जी', conditions: 'बीमारी', medications: 'चालू दवाई', bloodGroup: 'खून समूह', emergencyContact: 'आपातकालीन संपर्क', save: 'सेव करीं', updated: 'प्रोफ़ाइल अपडेट भइल' },
  common: { loading: 'लोड हो रहल बा...', error: 'कुछ गलत हो गइल', retry: 'फेर से करीं', save: 'सेव करीं', cancel: 'रद्द करीं', delete: 'मिटाईं', edit: 'बदलीं', close: 'बंद करीं', back: 'पीछे', next: 'अगला', submit: 'जमा करीं', viewAll: 'सब देखीं', noData: 'कवनो डेटा नइखे' },
}
