export default {
  nav: { home: 'முகப்பு', search: 'தேடு', dashboard: 'டாஷ்போர்டு', profile: 'சுயவிவரம்', login: 'உள்நுழை', register: 'பதிவு', logout: 'வெளியேறு', about: 'எங்களைப் பற்றி', contact: 'தொடர்பு', language: 'மொழி', pharmacyMap: 'மருந்தகம் வரைபடம்', interactions: 'மருந்து தொடர்பு', healthProfile: 'சுகாதார சுயவிவரம்', expiryTracker: 'காலாவதி கண்காணிப்பு', prescriptionScan: 'மருத்துவச்சீட்டு ஸ்கேன்', verifyMedicine: 'மருந்து சரிபார்ப்பு', trending: 'டிரெண்டிங்', priceCompare: 'விலை ஒப்பீடு', orders: 'எனது ஆர்டர்கள்' },
  home: { title: 'உங்கள் ஸ்மார்ட் மருந்து உதவியாளர்', subtitle: 'மருந்துகளைக் கண்டறியுங்கள், விலைகளை ஒப்பிடுங்கள், சுகாதார தகவல்கள் பெறுங்கள் — எல்லாம் ஒரே இடத்தில்.', searchPlaceholder: 'மருந்துகள், அறிகுறிகள், அல்லது சுகாதார கேள்விகள் தேடுங்கள்...', features: 'அம்சங்கள்', cta: 'தொடங்குங்கள்' },
  search: { title: 'மருந்துகள் தேடுங்கள்', placeholder: 'பெயர், பிரா recentண்டு, அல்லது கலவை மூலம் தேடுங்கள்...', results: 'முடிவுகள்', noResults: 'முடிவுகள் இல்லை', tryAgain: 'வேறு சொல்லை முயற்சிக்கவும்' },
  medicine: { name: 'மருந்து பெயர்', brand: 'பிராண்டு', composition: 'கலவை', price: 'விலை', stock: 'இருப்பு', available: 'கிடைக்கிறது', limited: 'குறைவு', outOfStock: 'இருப்பில் இல்லை', prescription: 'மருத்துவச்சீட்டு தேவை', precautions: 'முன்னெச்சரிக்கைகள்', sideEffects: 'பக்கவிளைவுகள்', uses: 'பயன்கள்', alternatives: 'மாற்றுகள்', dosage: 'அளவு', manufacturer: 'உற்பத்தியாளர்' },
  pharmacy: { name: 'மருந்தகம்', distance: 'தூரம்', rating: 'மதிப்பீடு', open: 'இப்போது திறந்துள்ளது', closed: 'மூடப்பட்டது', directions: 'வழிகாட்டல்', timings: 'நேரம்', verified: 'சரிபார்க்கப்பட்டது', call: 'அழைக்கவும்' },
  interactions: { title: 'மருந்து தொடர்பு சோதிப்பான்', subtitle: 'உங்கள் மருந்துகளை ஒன்றாக எடுப்பது பாதுகாப்பானதா என்று சரிபார்க்கவும்', addMedicine: 'மருந்து சேர்', checkInteractions: 'தொடர்புகளை சரிபார்', safe: 'பாதுகாப்பு', caution: 'எச்சரிக்கையாக பயன்படுத்தவும்', risky: 'ஆபத்தான கலவை', dangerous: 'மிக ஆபத்தானது', noInteractions: 'அறியப்பட்ட தொடர்புகள் இல்லை', severity: 'தீவிரம்', recommendation: 'பரிந்துரை' },
  healthProfile: { title: 'சுகாதார சுயவிவரம்', subtitle: 'தனிப்பட்ட பரிந்துரைகளுக்கு உங்கள் சுகாதார தகவல்களை நிர்வகிக்கவும்', allergies: 'ஒவ்வாமைகள்', conditions: 'மருத்துவ நிலைகள்', medications: 'தற்போதைய மருந்துகள்', bloodGroup: 'இரத்த வகை', emergencyContact: 'அவசர தொடர்பு', save: 'சுயவிவரம் சேமி', updated: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது' },
  common: { loading: 'ஏற்றுகிறது...', error: 'ஏதோ தவறு', retry: 'மீண்டும் முயற்சி', save: 'சேமி', cancel: 'ரத்து', delete: 'நீக்கு', edit: 'திருத்து', close: 'மூடு', back: 'பின்', next: 'அடுத்து', submit: 'சமர்ப்பி', viewAll: 'எல்லாம் காண்', noData: 'தரவு இல்லை' },
}
