export default {
  nav: { home: 'హోమ్', search: 'వెతకండి', dashboard: 'డాష్‌బోర్డ్', profile: 'ప్రొఫైల్', login: 'లాగిన్', register: 'నమోదు', logout: 'లాగౌట్', about: 'మా గురించి', contact: 'సంప్రదించండి', language: 'భాష', pharmacyMap: 'ఫార్మసీ మ్యాప్', interactions: 'మందుల ఇంటరాక్షన్', healthProfile: 'ఆరోగ్య ప్రొఫైల్', expiryTracker: 'గడువు ట్రాకర్', prescriptionScan: 'ప్రిస్క్రిప్షన్ స్కాన్', verifyMedicine: 'మందు ధృవీకరణ', trending: 'ట్రెండింగ్', priceCompare: 'ధర పోలిక', orders: 'నా ఆర్డర్లు' },
  home: { title: 'మీ స్మార్ట్ మందుల సహచరుడు', subtitle: 'మందులు కనుగొనండి, ధరలు పోల్చండి, ఆరోగ్య సమాచారం పొందండి — అంతా ఒకే చోట.', searchPlaceholder: 'మందులు, లక్షణాలు, లేదా ఆరోగ్య ప్రశ్నలు వెతకండి...', features: 'ఫీచర్లు', cta: 'ప్రారంభించండి' },
  search: { title: 'మందులు వెతకండి', placeholder: 'పేరు, బ్రాండ్, లేదా కూర్పు ద్వారా వెతకండి...', results: 'ఫలితాలు', noResults: 'ఫలితాలు లేవు', tryAgain: 'వేరే పదం ప్రయత్నించండి' },
  medicine: { name: 'మందు పేరు', brand: 'బ్రాండ్', composition: 'కూర్పు', price: 'ధర', stock: 'స్టాక్', available: 'అందుబాటులో', limited: 'పరిమితం', outOfStock: 'స్టాక్ లేదు', prescription: 'ప్రిస్క్రిప్షన్ అవసరం', precautions: 'జాగ్రత్తలు', sideEffects: 'దుష్ప్రభావాలు', uses: 'ఉపయోగాలు', alternatives: 'ప్రత్యామ్నాయాలు', dosage: 'మోతాదు', manufacturer: 'తయారీదారు' },
  pharmacy: { name: 'ఫార్మసీ', distance: 'దూరం', rating: 'రేటింగ్', open: 'ఇప్పుడు తెరిచి ఉంది', closed: 'మూసి ఉంది', directions: 'దిశలు', timings: 'సమయాలు', verified: 'ధృవీకరించబడింది', call: 'కాల్ చేయండి' },
  interactions: { title: 'మందుల ఇంటరాక్షన్ చెకర్', subtitle: 'మీ మందులు కలిపి తీసుకోవడం సురక్షితమా అని తనిఖీ చేయండి', addMedicine: 'మందు జోడించండి', checkInteractions: 'ఇంటరాక్షన్లు తనిఖీ చేయండి', safe: 'సురక్షితం', caution: 'జాగ్రత్తగా వాడండి', risky: 'ప్రమాదకరం', dangerous: 'అత్యంత ప్రమాదకరం', noInteractions: 'తెలిసిన ఇంటరాక్షన్లు లేవు', severity: 'తీవ్రత', recommendation: 'సిఫారసు' },
  healthProfile: { title: 'ఆరోగ్య ప్రొఫైల్', subtitle: 'వ్యక్తిగత సిఫారసుల కోసం మీ ఆరోగ్య సమాచారాన్ని నిర్వహించండి', allergies: 'అలెర్జీలు', conditions: 'వైద్య పరిస్థితులు', medications: 'ప్రస్తుత మందులు', bloodGroup: 'రక్త సమూహం', emergencyContact: 'అత్యవసర సంప్రదింపు', save: 'ప్రొఫైల్ సేవ్ చేయండి', updated: 'ప్రొఫైల్ విజయవంతంగా నవీకరించబడింది' },
  common: { loading: 'లోడ్ అవుతోంది...', error: 'ఏదో తప్పు జరిగింది', retry: 'మళ్ళీ ప్రయత్నించండి', save: 'సేవ్', cancel: 'రద్దు', delete: 'తొలగించు', edit: 'సవరించు', close: 'మూసివేయి', back: 'వెనుకకు', next: 'తరువాత', submit: 'సమర్పించు', viewAll: 'అన్నీ చూడండి', noData: 'డేటా అందుబాటులో లేదు' },
}
