// ── Drug Interaction Seed Data ──────────────────────────────────────
// Pairs are stored as lowercase composition/generic names
const interactions = [
  // ── Contraindicated (most dangerous) ──
  { drug1: 'warfarin', drug2: 'aspirin', severity: 'contraindicated', description: 'Combining warfarin with aspirin significantly increases the risk of bleeding, including internal and gastrointestinal bleeding.', recommendation: 'Avoid combining unless specifically prescribed by a specialist. Use alternative pain relief like paracetamol.', mechanism: 'Both drugs inhibit clotting through different mechanisms, compounding the anticoagulant effect.', onsetTime: 'Hours' },
  { drug1: 'methotrexate', drug2: 'ibuprofen', severity: 'contraindicated', description: 'NSAIDs like ibuprofen reduce renal clearance of methotrexate, potentially leading to toxic methotrexate levels.', recommendation: 'Avoid NSAIDs with methotrexate. Use paracetamol for pain if needed.', mechanism: 'Reduced renal excretion of methotrexate.', onsetTime: 'Days' },
  { drug1: 'sildenafil', drug2: 'nitroglycerin', severity: 'contraindicated', description: 'Combining PDE5 inhibitors with nitrates can cause severe, life-threatening hypotension.', recommendation: 'Never combine these medications. Wait at least 24-48 hours between use.', mechanism: 'Both cause vasodilation through nitric oxide pathway.', onsetTime: 'Immediate' },
  { drug1: 'maoi', drug2: 'ssri', severity: 'contraindicated', description: 'Combining MAO inhibitors with SSRIs can cause serotonin syndrome, a potentially fatal condition.', recommendation: 'Allow at least 14-day washout period between MAOIs and SSRIs.', mechanism: 'Excessive serotonin accumulation in the brain.', onsetTime: 'Hours' },

  // ── Severe ──
  { drug1: 'aspirin', drug2: 'ibuprofen', severity: 'severe', description: 'Both are NSAIDs. Taking them together increases the risk of GI bleeding and reduces the cardioprotective effect of aspirin.', recommendation: 'Avoid combining. If both needed, take aspirin 30 min before ibuprofen.', mechanism: 'Ibuprofen competes with aspirin for COX-1 binding.', onsetTime: 'Hours' },
  { drug1: 'metformin', drug2: 'alcohol', severity: 'severe', description: 'Alcohol increases the risk of lactic acidosis with metformin, a rare but serious side effect.', recommendation: 'Limit alcohol consumption. Avoid binge drinking completely.', mechanism: 'Both impair hepatic lactate metabolism.', onsetTime: 'Hours' },
  { drug1: 'ciprofloxacin', drug2: 'theophylline', severity: 'severe', description: 'Ciprofloxacin inhibits theophylline metabolism, potentially causing theophylline toxicity (seizures, arrhythmias).', recommendation: 'Monitor theophylline levels closely. Consider dose reduction or alternative antibiotic.', mechanism: 'CYP1A2 inhibition by ciprofloxacin.', onsetTime: 'Days' },
  { drug1: 'clopidogrel', drug2: 'omeprazole', severity: 'severe', description: 'Omeprazole reduces the antiplatelet effectiveness of clopidogrel by inhibiting its activation.', recommendation: 'Use pantoprazole instead of omeprazole with clopidogrel.', mechanism: 'CYP2C19 inhibition reduces clopidogrel activation.', onsetTime: 'Days' },
  { drug1: 'simvastatin', drug2: 'clarithromycin', severity: 'severe', description: 'Clarithromycin inhibits statin metabolism, increasing risk of rhabdomyolysis (muscle breakdown).', recommendation: 'Temporarily stop statin during clarithromycin course, or use azithromycin instead.', mechanism: 'CYP3A4 inhibition increases statin blood levels.', onsetTime: 'Days' },
  { drug1: 'atorvastatin', drug2: 'clarithromycin', severity: 'severe', description: 'Clarithromycin inhibits statin metabolism, increasing risk of myopathy and rhabdomyolysis.', recommendation: 'Use azithromycin as alternative, or temporarily suspend statin.', mechanism: 'CYP3A4 inhibition increases statin levels.', onsetTime: 'Days' },
  { drug1: 'alprazolam', drug2: 'alcohol', severity: 'severe', description: 'Combining benzodiazepines with alcohol causes severe CNS depression, respiratory failure, and potential death.', recommendation: 'Never combine. Avoid alcohol completely while on benzodiazepines.', mechanism: 'Additive GABA-ergic CNS depression.', onsetTime: 'Immediate' },
  { drug1: 'digoxin', drug2: 'amiodarone', severity: 'severe', description: 'Amiodarone increases digoxin levels by 70-100%, risking digoxin toxicity (arrhythmias, nausea).', recommendation: 'Reduce digoxin dose by 50% when starting amiodarone. Monitor digoxin levels.', mechanism: 'Reduced renal and non-renal clearance of digoxin.', onsetTime: 'Days' },
  { drug1: 'lithium', drug2: 'ibuprofen', severity: 'severe', description: 'NSAIDs reduce lithium excretion, potentially causing lithium toxicity (tremor, confusion, kidney damage).', recommendation: 'Avoid NSAIDs. Use paracetamol for pain. Monitor lithium levels if NSAID is essential.', mechanism: 'Reduced renal prostaglandin synthesis decreases lithium clearance.', onsetTime: 'Days' },

  // ── Moderate ──
  { drug1: 'paracetamol', drug2: 'warfarin', severity: 'moderate', description: 'Regular paracetamol use can enhance the anticoagulant effect of warfarin, increasing bleeding risk.', recommendation: 'Occasional use is safe. Monitor INR if using paracetamol regularly (>2g/day for >3 days).', mechanism: 'Paracetamol may inhibit vitamin K-dependent clotting factor synthesis.', onsetTime: 'Days' },
  { drug1: 'metformin', drug2: 'glimepiride', severity: 'moderate', description: 'Combining two antidiabetics increases the risk of hypoglycemia (dangerously low blood sugar).', recommendation: 'Monitor blood sugar frequently. Adjust doses carefully. Keep glucose tablets handy.', mechanism: 'Additive blood sugar lowering effect.', onsetTime: 'Hours' },
  { drug1: 'amlodipine', drug2: 'atenolol', severity: 'moderate', description: 'Both lower blood pressure and heart rate. Combination may cause excessive hypotension or bradycardia.', recommendation: 'Monitor blood pressure and heart rate regularly. Dose adjustments may be needed.', mechanism: 'Additive cardiovascular depression.', onsetTime: 'Hours' },
  { drug1: 'losartan', drug2: 'potassium', severity: 'moderate', description: 'ARBs like losartan can increase potassium levels. Additional potassium supplements risk hyperkalemia.', recommendation: 'Monitor serum potassium levels. Avoid potassium supplements unless directed.', mechanism: 'ARBs reduce aldosterone-mediated potassium excretion.', onsetTime: 'Days' },
  { drug1: 'ciprofloxacin', drug2: 'calcium', severity: 'moderate', description: 'Calcium-containing products reduce ciprofloxacin absorption by 30-50%, reducing antibiotic effectiveness.', recommendation: 'Take ciprofloxacin 2 hours before or 6 hours after calcium supplements or dairy.', mechanism: 'Chelation of ciprofloxacin by divalent cations.', onsetTime: 'Immediate' },
  { drug1: 'azithromycin', drug2: 'antacid', severity: 'moderate', description: 'Antacids reduce azithromycin absorption, potentially reducing its effectiveness.', recommendation: 'Take azithromycin 1 hour before or 2 hours after antacids.', mechanism: 'Reduced GI absorption due to pH changes.', onsetTime: 'Immediate' },
  { drug1: 'levothyroxine', drug2: 'calcium', severity: 'moderate', description: 'Calcium supplements reduce levothyroxine absorption, affecting thyroid control.', recommendation: 'Separate doses by at least 4 hours. Take levothyroxine on an empty stomach.', mechanism: 'Calcium forms insoluble complexes with levothyroxine in the GI tract.', onsetTime: 'Hours' },
  { drug1: 'levothyroxine', drug2: 'iron', severity: 'moderate', description: 'Iron supplements significantly reduce levothyroxine absorption.', recommendation: 'Separate doses by at least 4 hours. Take levothyroxine first thing in the morning.', mechanism: 'Iron chelates levothyroxine forming non-absorbable complexes.', onsetTime: 'Hours' },
  { drug1: 'escitalopram', drug2: 'tramadol', severity: 'moderate', description: 'Combining SSRIs with tramadol increases the risk of serotonin syndrome and seizures.', recommendation: 'Use with caution. Monitor for symptoms: agitation, confusion, rapid heartbeat, muscle twitching.', mechanism: 'Additive serotonergic effects.', onsetTime: 'Hours' },
  { drug1: 'diclofenac', drug2: 'aspirin', severity: 'moderate', description: 'Both are NSAIDs. Combined use increases GI bleeding risk without additional benefit.', recommendation: 'Avoid taking together. Choose one NSAID based on clinical need.', mechanism: 'Additive COX inhibition and GI mucosal damage.', onsetTime: 'Hours' },
  { drug1: 'amoxicillin', drug2: 'methotrexate', severity: 'moderate', description: 'Amoxicillin may reduce methotrexate excretion, increasing risk of toxicity.', recommendation: 'Monitor for methotrexate toxicity. Consider alternative antibiotic.', mechanism: 'Competition for renal tubular secretion.', onsetTime: 'Days' },
  { drug1: 'prednisolone', drug2: 'ibuprofen', severity: 'moderate', description: 'Combining corticosteroids with NSAIDs significantly increases the risk of GI ulceration and bleeding.', recommendation: 'Use gastroprotective agent (omeprazole/pantoprazole) if combination is necessary.', mechanism: 'Both impair GI mucosal defense mechanisms.', onsetTime: 'Days' },
  { drug1: 'gabapentin', drug2: 'pregabalin', severity: 'moderate', description: 'Both are gabapentinoids with similar mechanisms. Combination increases side effects without benefit.', recommendation: 'Do not combine. Use one or the other, not both.', mechanism: 'Duplicate pharmacological action on calcium channels.', onsetTime: 'Hours' },

  // ── Mild ──
  { drug1: 'paracetamol', drug2: 'caffeine', severity: 'mild', description: 'Caffeine can enhance the analgesic effect of paracetamol. Generally a beneficial interaction.', recommendation: 'Safe combination. Some formulations intentionally combine both.', mechanism: 'Caffeine enhances GI absorption and central analgesic effect.', onsetTime: 'Immediate' },
  { drug1: 'cetirizine', drug2: 'paracetamol', severity: 'mild', description: 'No significant interaction. These can be safely combined for cold/flu with allergy symptoms.', recommendation: 'Safe to use together. Standard combination for cold relief.', mechanism: 'No pharmacological interaction.', onsetTime: 'N/A' },
  { drug1: 'omeprazole', drug2: 'paracetamol', severity: 'mild', description: 'Minimal interaction. Omeprazole may slightly increase paracetamol absorption.', recommendation: 'Safe combination. No dose adjustment needed.', mechanism: 'Altered gastric pH may slightly affect absorption rate.', onsetTime: 'Hours' },
  { drug1: 'vitamin d3', drug2: 'calcium', severity: 'mild', description: 'Vitamin D3 enhances calcium absorption. This is a beneficial interaction.', recommendation: 'Recommended combination for bone health. Many formulations combine both.', mechanism: 'Vitamin D increases intestinal calcium absorption.', onsetTime: 'Days' },
  { drug1: 'metformin', drug2: 'vitamin b12', severity: 'mild', description: 'Long-term metformin use can reduce vitamin B12 absorption, potentially causing deficiency.', recommendation: 'Consider B12 supplementation with long-term metformin use. Monitor B12 levels annually.', mechanism: 'Metformin reduces ileal B12 absorption via calcium-dependent mechanism.', onsetTime: 'Months' },
  { drug1: 'iron', drug2: 'vitamin c', severity: 'mild', description: 'Vitamin C significantly enhances iron absorption. This is a beneficial interaction.', recommendation: 'Take iron supplements with vitamin C or citrus juice for better absorption.', mechanism: 'Ascorbic acid converts ferric iron to the more absorbable ferrous form.', onsetTime: 'Immediate' },
  { drug1: 'amoxicillin', drug2: 'probiotics', severity: 'mild', description: 'Antibiotics kill beneficial gut bacteria. Probiotics help restore gut flora.', recommendation: 'Take probiotics 2 hours after antibiotics. Continue for 1 week after completing course.', mechanism: 'Antibiotics disrupt gut microbiome; probiotics replenish it.', onsetTime: 'Days' },
  { drug1: 'cetirizine', drug2: 'montelukast', severity: 'mild', description: 'No harmful interaction. Often prescribed together for allergic rhinitis and asthma.', recommendation: 'Safe and commonly prescribed combination for allergy management.', mechanism: 'Complementary mechanisms (antihistamine + leukotriene antagonist).', onsetTime: 'N/A' },
  { drug1: 'pantoprazole', drug2: 'domperidone', severity: 'mild', description: 'No significant interaction. Both are often co-prescribed for GERD with nausea.', recommendation: 'Safe combination. Take pantoprazole before meals and domperidone 15-30 min before meals.', mechanism: 'Complementary mechanisms for GI symptom relief.', onsetTime: 'N/A' },
  { drug1: 'amlodipine', drug2: 'losartan', severity: 'mild', description: 'Often prescribed together for better blood pressure control. Generally a safe combination.', recommendation: 'Common and effective combination for hypertension. Monitor blood pressure regularly.', mechanism: 'Complementary mechanisms (calcium channel + ARB) for additive BP lowering.', onsetTime: 'Hours' },
];

module.exports = { interactions };
